#!/bin/sh

__N2038_PATH_TO_THIS_SCRIPT_FROM_ENVIRONMENT_ROOT="scripts/programs/jetbrains/_constants.sh"

# Required before imports
# shellcheck disable=SC1091
if [ "${_N2038_IS_MY_SHELL_ENVIRONMENT_INITIALIZED}" != "1" ]; then
  # If we have not initialized the shell environment, but has it (for example, when starting "dash" from "bash"), then we will try to initialize it.
  if [ -n "${_N2038_SHELL_ENVIRONMENT_PATH}" ]; then
    . "${_N2038_SHELL_ENVIRONMENT_PATH}/n2038_my_shell_environment.sh" || _n2038_return "$?" || return "$?"
  else
    echo "\"my-bash-environment\" is not initialized. Please, initialize it first." >&2 && return 1 2> /dev/null || exit 1
  fi
fi
_n2038_required_before_imports || { __n2038_return_code="$?" && [ "${__n2038_return_code}" = "${_N2038_RETURN_CODE_WHEN_FILE_IS_ALREADY_SOURCED}" ] && return "${_N2038_RETURN_CODE_WHEN_FILE_IS_ALREADY_SOURCED}" || _n2038_return "${__n2038_return_code}" || return "$?"; }

# Imports
# ...

# Required after imports
_n2038_required_after_imports || _n2038_return "$?" || return "$?"

_N2038_JETBRAINS_PRODUCT_NAME_IDEA="idea"
_N2038_JETBRAINS_PRODUCT_NAME_PHPSTORM="phpstorm"
_N2038_JETBRAINS_PRODUCT_NAME_CLION="clion"
_N2038_JETBRAINS_PRODUCT_NAME_PYCHARM="pycharm"
_N2038_JETBRAINS_PRODUCT_NAME_WEBSTORM="webstorm"
_N2038_JETBRAINS_PRODUCT_NAME_RIDER="rider"
_N2038_JETBRAINS_PRODUCT_NAME_RUBYMINE="rubymine"
_N2038_JETBRAINS_PRODUCT_NAME_RUSTROVER="rustrover"
_N2038_JETBRAINS_PRODUCT_NAME_WRITERSIDE="writerside"
_N2038_JETBRAINS_PRODUCT_NAME_DATAGRIP="datagrip"
_N2038_JETBRAINS_PRODUCT_NAME_DATASPELL="dataspell"
_N2038_JETBRAINS_PRODUCT_NAME_FLEET="fleet"
_N2038_JETBRAINS_PRODUCT_NAME_GOLAND="goland"

_N2038_JETBRAINS_PRODUCTS="${_N2038_JETBRAINS_PRODUCT_NAME_IDEA}
${_N2038_JETBRAINS_PRODUCT_NAME_PHPSTORM}
${_N2038_JETBRAINS_PRODUCT_NAME_CLION}
${_N2038_JETBRAINS_PRODUCT_NAME_PYCHARM}
${_N2038_JETBRAINS_PRODUCT_NAME_WEBSTORM}
${_N2038_JETBRAINS_PRODUCT_NAME_RIDER}
${_N2038_JETBRAINS_PRODUCT_NAME_RUBYMINE}
${_N2038_JETBRAINS_PRODUCT_NAME_RUSTROVER}
${_N2038_JETBRAINS_PRODUCT_NAME_WRITERSIDE}
${_N2038_JETBRAINS_PRODUCT_NAME_DATAGRIP}
${_N2038_JETBRAINS_PRODUCT_NAME_DATASPELL}
${_N2038_JETBRAINS_PRODUCT_NAME_FLEET}
${_N2038_JETBRAINS_PRODUCT_NAME_GOLAND}"

_N2038_JETBRAINS_DOWNLOAD_TYPE_LINUX_ARM64="linuxARM64"
_N2038_JETBRAINS_DOWNLOAD_TYPE_LINUX="linux"
_N2038_JETBRAINS_DOWNLOAD_TYPE_THIRD_PARTY_LIBRARIES_JSON="thirdPartyLibrariesJson"
_N2038_JETBRAINS_DOWNLOAD_TYPE_WINDOWS="windows"
_N2038_JETBRAINS_DOWNLOAD_TYPE_WINDOWS_ZIP="windowsZip"
_N2038_JETBRAINS_DOWNLOAD_TYPE_WINDOWS_ARM64="windowsARM64"
_N2038_JETBRAINS_DOWNLOAD_TYPE_MAC="mac"
_N2038_JETBRAINS_DOWNLOAD_TYPE_MAC_M1="macM1"

_N2038_JETBRAINS_DOWNLOAD_TYPES="${_N2038_JETBRAINS_DOWNLOAD_TYPE_LINUX_ARM64}
${_N2038_JETBRAINS_DOWNLOAD_TYPE_LINUX}
${_N2038_JETBRAINS_DOWNLOAD_TYPE_THIRD_PARTY_LIBRARIES_JSON}
${_N2038_JETBRAINS_DOWNLOAD_TYPE_WINDOWS}
${_N2038_JETBRAINS_DOWNLOAD_TYPE_WINDOWS_ZIP}
${_N2038_JETBRAINS_DOWNLOAD_TYPE_WINDOWS_ARM64}
${_N2038_JETBRAINS_DOWNLOAD_TYPE_MAC}
${_N2038_JETBRAINS_DOWNLOAD_TYPE_MAC_M1}"

# Required after function
_n2038_required_after_function || _n2038_return "$?" || return "$?"
